// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "f49ce2f8-b3da-44d4-bfd0-475c1bbcd50e";

const char SSID[]               = "ABC";    // Network SSID (name)
const char PASS[]               = "12345678";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "MV@eT6xt78FdKmzW@GH7yO1wT";    // Secret device password

void onGreenChange();

bool green;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(green, READWRITE, ON_CHANGE, onGreenChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
